name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: npm i
        run: npm i

      - name: Run pre-commit script
        run: npm run pre:commit
